[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.backend.txt"]

[phases.build]
cmds = ["echo 'Skipping frontend build on backend'"]

[start]
cmd = "python3 main.py"
